#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	
	if [ "systemd" == "$INITSYS" ]; then
		ln -s /usr/lib/dshldesk/dshldesk /usr/bin/dshldesk

		if [ -e /etc/systemd/system/dshldesk.service ]; then
			rm /etc/systemd/system/dshldesk.service /usr/lib/systemd/system/dshldesk.service /usr/lib/systemd/user/dshldesk.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/dshldesk/files/systemd/dshldesk.service /usr/lib/systemd/system/dshldesk.service
		systemctl daemon-reload
		systemctl enable dshldesk
		systemctl start dshldesk
	fi
fi
