#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	
	if [ "systemd" == "$INITSYS" ]; then
		ln -s /usr/lib/dshelpdesk/dshelpdesk /usr/bin/dshelpdesk

		if [ -e /etc/systemd/system/dshelpdesk.service ]; then
			rm /etc/systemd/system/dshelpdesk.service /usr/lib/systemd/system/dshelpdesk.service /usr/lib/systemd/user/dshelpdesk.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/dshelpdesk/files/systemd/dshelpdesk.service /usr/lib/systemd/system/dshelpdesk.service
		systemctl daemon-reload
		systemctl enable dshelpdesk
		systemctl start dshelpdesk
	fi
fi
